name: Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  deploy-sandbox:
    name: Deploy Sandbox Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Sandbox Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy \
            --only hosting \
            --project sandbox-56be2 \
            --non-interactive
